name: finalproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.9.1
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  just_audio: ^0.9.34
  audio_video_progress_bar: ^1.0.0
  cached_network_image: ^3.3.0
  build_runner: ^2.4.9

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/Synapse Music Logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/Synapse Music Logo.png"
  adaptive_icon_background: "#0D1117"  # Transparent background
  adaptive_icon_foreground: "assets/images/Synapse Music Logo.png"
