  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
                'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDtILO7_LPbIHvgKiN-Jf6FoWN_6Xgu4ww',
      appId: '1:1015225141954:web:7228841c51367113bdc95b',
      messagingSenderId: '1015225141954',
      projectId: 'finalproject-cceb9',
      authDomain: 'finalproject-cceb9.firebaseapp.com',
      storageBucket: 'finalproject-cceb9.firebasestorage.app',
      measurementId: 'G-4T7RV4JDH3',
    );

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDfxBz1BtI-zOSt8ZEbxrn5wI-5fx4haxs',
      appId: '1:1015225141954:android:3f1403c404704b55bdc95b',
      messagingSenderId: '1015225141954',
      projectId: 'finalproject-cceb9',
      storageBucket: 'finalproject-cceb9.firebasestorage.app',
    );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyCZfj77y2UvrV4-n6C1WmFjI2xzFTJNvWc',
      appId: '1:1015225141954:ios:52a6ddbfbeda70d9bdc95b',
      messagingSenderId: '1015225141954',
      projectId: 'finalproject-cceb9',
      storageBucket: 'finalproject-cceb9.firebasestorage.app',
      iosBundleId: 'com.example.finalproject',
    );

    static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyCZfj77y2UvrV4-n6C1WmFjI2xzFTJNvWc',
      appId: '1:1015225141954:ios:52a6ddbfbeda70d9bdc95b',
      messagingSenderId: '1015225141954',
      projectId: 'finalproject-cceb9',
      storageBucket: 'finalproject-cceb9.firebasestorage.app',
      iosBundleId: 'com.example.finalproject',
    );

    static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyDtILO7_LPbIHvgKiN-Jf6FoWN_6Xgu4ww',
      appId: '1:1015225141954:web:8fcd0326eda9f5f6bdc95b',
      messagingSenderId: '1015225141954',
      projectId: 'finalproject-cceb9',
      authDomain: 'finalproject-cceb9.firebaseapp.com',
      storageBucket: 'finalproject-cceb9.firebasestorage.app',
      measurementId: 'G-D4BDFLCPZ4',
    );
  }
